# .pre-commit-config.yaml
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.3
  hooks:
    - id: ruff-format
    - id: ruff
      args: [--fix-only]
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.79.0
  hooks:
    - id: terraform_fmt
