name: ci
on: [push, pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install uv globally
      - name: Install uv
        run: pip install uv

      - name: Install deps
        run: |
          uv pip install -r requirements.lock -e ".[dev]"

      - name: Ruff format check
        run: ruff format --check .

      - name: Ruff lint
        run: ruff check .

      - name: Tests
        run: pytest -q
